# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# misc places we keep binaries
export PATH=$HOME/local/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/google-cloud-sdk/bin:$PATH
export PATH=/usr/local/share/python:$PATH
