# misc places we keep binaries
export PATH=$HOME/local/bin:$PATH
# pip uses this when you install with --use
export PATH=$HOME/.local/bin:$PATH
export PATH=/usr/local/bin:$PATH
# tmuxifier
export PATH="$HOME/.tmuxifier/bin:$PATH"
# google sdk
export PATH="$HOME/local/google-cloud-sdk/bin:$PATH"
# yarn
if [ $commands[yarn] ]; then
  export PATH="$PATH:`yarn global bin`"
fi

if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi

export PATH=`echo $PATH | tr ':' '\n' | awk '($0!~/mnt\/c/) {print} ' | tr '\n' ':'`
