# we do this to workaround the problem described here
# but this could come into play w/ other tools in
# combination w/ tmux so it's good generally.
# https://github.com/sstephenson/rbenv/issues/369

# note: seems not to affect linux, could drop it
# completely if/when we don't care about osx

if [[ `uname` != 'Linux' ]]; then
  if [ -f /etc/profile ]; then
    PATH=""
    source /etc/profile
  fi
fi
