setopt prompt_subst
setopt hist_ignore_dups

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt extendedglob notify
setopt append_history
setopt inc_append_history
unsetopt autocd
bindkey -e

autoload -Uz compinit
compinit
setopt complete_in_word

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

export WORDCHARS='*?[]~=&;!#$%^(){}'

bindkey '^' self-insert-backslash
function self-insert-backslash() { LBUFFER+='\'; zle .self-insert }
zle -N self-insert-backslash

tmux_name_window_after_directory() {
  tmux rename-window -t${TMUX_PANE} `basename $PWD`
}

tmux_name_window() {
  tmux rename-window -t${TMUX_PANE} `basename $1`
}

grep_history() {
  cat ~/.zsh_history | grep $1
}

# pip uses this when you install with --use
export PATH=$HOME/.local/bin:$PATH
# for personal scripts
export PATH=$HOME/local/bin:$PATH
