# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

if [ -e "$HOME/.private-aliases" ]; then
  source "$HOME/.private-aliases"
fi

# ignore duplicate history entries
setopt histignoredups

# allow comments in shell
setopt interactivecomments

# keep TONS of history
export HISTSIZE=4096

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# Enable extended globbing
setopt EXTENDED_GLOB

# use vim as an editor
export EDITOR='vim'

if [ -f $HOME/.private_env ]; then
  source $HOME/.private_env
fi

# Use z
. `brew --prefix`/etc/profile.d/z.sh

# Use nvm install via brew
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# For v.com
ulimit -n 4000

# levity
echo
echo "  (╯°□°)╯︵ ┻━┻  oops."
echo

s="/home/mike/code/course-api-toolbelt/main.sh"; test -f $s && source $s
