# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

if [ -e "$HOME/.private-aliases" ]; then
  source "$HOME/.private-aliases"
fi

# ignore duplicate history entries
setopt histignoredups

# allow comments in shell
setopt interactivecomments

# keep TONS of history
export HISTSIZE=4096

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# Enable extended globbing
setopt EXTENDED_GLOB

# use vim as an editor
export EDITOR='vim'

if [ -f $HOME/.private_env ]; then
  source $HOME/.private_env
fi

# Use nvm install via brew
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Lame but we have this defined in `bin/web` also
web_env() {
  source $(brew --prefix nvm)/nvm.sh
  cd ${HOME}/code/versal.com
  nvm use 0.10
  ulimit -n 4096
}

# levity
echo
echo "  (╯°□°)╯︵ ┻━┻  oops."
echo

s="/home/mike/code/course-api-toolbelt/main.sh"; test -f $s && source $s
