# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# ignore duplicate history entries
setopt histignoredups

# allow comments in shell
setopt interactivecomments

# keep TONS of history
export HISTSIZE=4096

setopt auto_cd

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# Enable extended globbing
setopt EXTENDED_GLOB

# use vim as an editor
export EDITOR='vim'

if [ -f $HOME/.private_env ]; then
  source $HOME/.private_env
fi

export PATH="$HOME/.yarn/bin:$PATH"

if [ -x "$(command -v hub)" ]; then
  eval "$(hub alias -s)"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source ${HOME}/.gitprompt
