session_name: dev
windows:
- window_name: app
  focus: true
  layout: main-vertical
  shell_command_before:
    - cd code/frontend
  panes:
    - shell_command: vim
      focus: true
    - npm run dev
    - npm run storybook
    - blank
- window_name: notes
  layout: main-vertical
  shell_command_before:
    - cd code/notes
  panes:
    - shell_command: vim home.md
      focus: true
    - nodemon --exec 'git pull && git add . ; git ci -amMisc ; git push -u' --watch home.md
- window_name: dotfiles
  layout: main-vertical
  shell_command_before:
    - cd code/dotfiles
  panes:
    - vim
    - blank
