session_name: dev
windows:
- window_name: app
  focus: true
  layout: main-vertical
  start_directory: code/frontend
  panes:
    - shell_command: vim
      focus: true
    - yarn dev
    - yarn tsc --watch
    - wpf 'yarn lint'
- window_name: notes
  layout: main-vertical
  start_directory: code/notes
  panes:
    - shell_command: vim home.md
      focus: true
    - nodemon --exec 'git pull ; git add . ; git ci -amMisc ; git push -u' --watch home.md
- window_name: dotfiles
  layout: main-vertical
  start_directory: code/dotfiles
  panes:
    - vim
